version: '3'

services:
  # FastAPI backend service
  fastapi-app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  # PostgreSQL database service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ievolve
      POSTGRES_USER: abdozaki
      POSTGRES_PASSWORD: zakiabdo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
