"""Initial migration

Revision ID: de51280f3272
Revises: 
Create Date: 2024-02-21 05:34:04.740369

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de51280f3272"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "habit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("day_plan", sa.Column("id", sa.UUID(), nullable=False))
    op.drop_column("day_plan", "dayplan_id")
    op.drop_column("day_plan", "dayplan")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_plan",
        sa.Column(
            "dayplan",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "day_plan",
        sa.Column("dayplan_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_column("day_plan", "id")
    op.drop_table("habit")
    # ### end Alembic commands ###
