"""l

Revision ID: c702a2a3d8e5
Revises: de51280f3272
Create Date: 2024-02-29 08:34:58.104271

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c702a2a3d8e5"
down_revision = "de51280f3272"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "day_plan",
        sa.Column("dayplan", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("day_plan", "dayplan")
    # ### end Alembic commands ###
