"""Initial migration

Revision ID: 285d1e1ef826
Revises: 2f5ac2bd4a70
Create Date: 2024-01-29 15:24:12.696303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "285d1e1ef826"
down_revision = "2f5ac2bd4a70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
