"""Initial migration

Revision ID: 2f5ac2bd4a70
Revises: 
Create Date: 2024-01-29 15:21:15.200127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f5ac2bd4a70"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_password", sa.String(length=128), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("latitude", sa.String(length=128), nullable=True),
        sa.Column("longitude", sa.String(length=128), nullable=True),
        sa.Column("address", sa.String(length=128), nullable=True),
        sa.Column("title", sa.String(length=10), nullable=True),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("avatar", sa.String(length=128), nullable=True),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=128), nullable=True),
        sa.Column("token", sa.String(length=128), nullable=True),
        sa.Column("last_access", sa.String(length=128), nullable=True),
        sa.Column("is_authenticated", sa.Boolean(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=True),
        sa.Column("is_chef", sa.Boolean(), nullable=True),
        sa.Column("is_driver", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("new_user", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "activity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("start", sa.Time(), nullable=True),
        sa.Column("end", sa.Time(), nullable=True),
        sa.Column("activity", sa.String(length=20), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("activity")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
