"""Initial migration

Revision ID: a63cda019bcc
Revises: 1b203edc11c4
Create Date: 2024-03-07 18:47:01.994134

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a63cda019bcc"
down_revision = "1b203edc11c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "today",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("full_score", sa.Integer(), nullable=True),
        sa.Column("current_score", sa.Integer(), nullable=True),
        sa.Column("activities", sa.JSON(), nullable=True),
        sa.Column("habits", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_index(op.f("ix_today_date"), "today", ["date"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_today_date"), table_name="today")
    op.drop_table("today")
    # ### end Alembic commands ###
