"""Initial migration

Revision ID: 64846a9687a5
Revises: 99ca05ebfb33
Create Date: 2024-02-20 22:33:51.924787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "64846a9687a5"
down_revision = "99ca05ebfb33"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "day_plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("full_score", sa.Integer(), nullable=True),
        sa.Column("total_score", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "habit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("habit")
    op.drop_table("day_plan")
    # ### end Alembic commands ###
