"""Initial migration

Revision ID: dffc07d26926
Revises: a63cda019bcc
Create Date: 2024-03-07 23:29:27.106891

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dffc07d26926"
down_revision = "a63cda019bcc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("today", sa.Column("user_id", sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(
        None, "today", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "today", type_="foreignkey")
    op.drop_column("today", "user_id")
    # ### end Alembic commands ###
