name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      
      -  name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
      - name: Push Docker image to Docker Hub
        run: docker push my-image-name:$(date +%s)
